### ISSUE TITLE
JavaScript group capstone: set up our Kanban board

### ISSUE THREAD

**Issue by Mofuhidy** [Mofuhidy/group-capstone-js#21]
[project link](https://github.com/Mofuhidy/group-capstone-js/projects/1)

- We are group of two members (Mofuhidy, Ayomide)

**Comment by Gambit142** [comment]
Hi @Mofuhidy @Paulinelali  👋,

## Status: Approved 🟢   

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉

### Highlights 
- Information about team members is available ✔️
- Link to the Kanban board is available ✔️   
- All cards are assigned to team members ✔️
- All tasks are assigned in a fair way ✔️

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

#### Please tag me in your question so I can receive the notification. You can tag me by typing @Gambit142

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
